services:
  app:
    image: ghcr.io/k1racle/taskflowpro:latest
    restart: unless-stopped
    ports:
      - "8085:80"
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      DB_HOST: db
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASS: ${MARIADB_PASSWORD}
    volumes:
      - taskflow_runtime_data:/var/www/html/runtime
      - taskflow_uploads_data:/var/www/html/uploads
      - taskflow_backups_data:/var/www/html/backups
      - taskflow_api_logs:/var/www/html/api/logs

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - taskflow_db_data:/var/lib/mysql

volumes:
  taskflow_db_data:
  taskflow_runtime_data:
  taskflow_uploads_data:
  taskflow_backups_data:
  taskflow_api_logs:
